version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ecommerce_nginx
    volumes:
      - ./src/ecommerce:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      php:
        condition: service_healthy
    networks:
      - ecommerce_network

  php:
    build:
      context: ./docker/php
      args:
        - DB_HOST=${DB_HOST}
        - DB_DATABASE=${DB_DATABASE}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
    container_name: ecommerce_php
    volumes:
      - ./src/ecommerce:/var/www/html
    networks:
      - ecommerce_network
    expose:
      - "9000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    build:
      context: ./docker/mysql
    container_name: ecommerce_mysql
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 15

volumes:
  mysql_data:
  app:

networks:
  ecommerce_network: